config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add this extension's routes here
  namespace :admin do
    resources :active_sales do
      collection do
        get  :eventables
        post :update_positions
      end
      member do
        get :get_children
      end
      resources :active_sale_events do
        member do
          put :update_events
        end
        resources :sale_images do
          collection do
            post :update_positions
          end
        end
      end
    end
  end
end

app/models/spree/sale_image.rb
module Spree
  class SaleImage < Asset
    validates_attachment_presence :attachment
    validate :no_attachment_errors

    attr_accessible :alt, :attachment, :position, :viewable_type, :viewable_id

    has_attached_file :attachment,
                      :styles => { :mini => '48x48>', :small => '100x100>', :sale => '240x240>', :large => '600x600>' },
                      :default_style => :sale,
                      :url => '/spree/sales/:id/:style/:basename.:extension',
                      :path => ':rails_root/public/spree/sales/:id/:style/:basename.:extension',
                      :convert_options => { :all => '-strip' }
    # save the w,h of the original image (from which others can be calculated)
    # we need to look at the write-queue for images which have not been saved yet
    after_post_process :find_dimensions

    include Spree::Core::S3Support
    supports_s3 :attachment

    Spree::Image.attachment_definitions[:attachment][:styles] = ActiveSupport::JSON.decode(Spree::Config[:attachment_styles])
    Spree::Image.attachment_definitions[:attachment][:path] = Spree::Config[:attachment_path]
    Spree::Image.attachment_definitions[:attachment][:url] = Spree::Config[:attachment_url]
    Spree::Image.attachment_definitions[:attachment][:default_url] = Spree::Config[:attachment_default_url]
    Spree::Image.attachment_definitions[:attachment][:default_style] = Spree::Config[:attachment_default_style]

    #used by admin sales autocomplete
    def mini_url
      attachment.url(:mini, false)
    end

    def find_dimensions
      temporary = attachment.queued_for_write[:original]
      filename = temporary.path unless temporary.nil?
      filename = attachment.path if filename.blank?
      geometry = Paperclip::Geometry.from_file(filename)
      self.attachment_width  = geometry.width
      self.attachment_height = geometry.height
    end

    # if there are errors from the plugin, then add a more meaningful message
    def no_attachment_errors
      unless attachment.errors.empty?
        # uncomment this to get rid of the less-than-useful interrim messages
        # errors.clear
        errors.add :attachment, "Paperclip returned errors for file '#{attachment_file_name}' - check ImageMagick installation or image source file."
        false
      end
    end

    def viewable_type=(event_type)
      super event_type.to_s.classify.constantize.base_class.to_s
    end
  end
end

app/controllers/spree/admin/sale_images_controller.rb
module Spree
  module Admin
    class SaleImagesController < ResourceController
      belongs_to 'spree/active_sale_event', :find_by => :id
      before_filter :load_data

      create.before :set_viewable
      update.before :set_viewable
      destroy.before :destroy_before

      private

        def location_after_save
          edit_admin_active_sale_active_sale_event_url(@active_sale_event.active_sale, @active_sale_event)
        end

        def load_data
          @active_sale = Spree::ActiveSale.find(params[:active_sale_id])
          @active_sale_event = Spree::ActiveSaleEvent.find(params[:active_sale_event_id])
        end

        def set_viewable
          @sale_image.viewable_type = 'Spree::ActiveSaleEvent'
          @sale_image.viewable_id = @active_sale_event.id
        end

        def destroy_before
          @viewable = @sale_image.viewable
        end

    end
  end
end

app/views/spree/admin/sale_images/_form.html.erb
<div data-hook="admin_image_form_fields">
  <div class="four columns alpha">
    <div data-hook="file" class="field">
      <%= f.label :attachment, Spree.t(:filename) %><br>
      <%= f.file_field :attachment %>
    </div>
  </div>
  <div data-hook="alt_text" class="field omega five columns">
    <%= f.label Spree.t(:alt_text) %><br>
    <%= f.text_area :alt, :rows => 4, :class => 'fullwidth' %>
  </div>
</div>

<div class="clear"></div>

<br/>

<%= render 'spree/admin/shared/sale_images' %>

app/views/spree/admin/sale_images/edit.html.erb
<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @sale_image } %>

<ul class="inline-menu">
  <li><%= button_link_to t('spree.active_sale.event.link.back'), edit_admin_active_sale_active_sale_event_url(@active_sale, @active_sale_event), :icon => 'icon-arrow-left' %></li>
</ul>

<%= form_for [:admin, @active_sale, @active_sale_event, @sale_image], :html => { :multipart => true } do |f| %>
  <fieldset data-hook="edit_image">
    <legend align="center"><%= @sale_image.attachment_file_name%></legend>
    <div data-hook="thumbnail" class="field alpha three columns align-center">
      <%= f.label Spree.t(:thumbnail) %><br>
      <%= link_to image_tag(@sale_image.attachment.url(:small)), @sale_image.attachment.url(:product) %>
    </div>
    <div class="nine columns omega">
      <%= render :partial => 'form', :locals => { :f => f } %>  
    </div>
    <div class="clear"></div>
    <div class="form-buttons filter-actions actions" data-hook="buttons">
      <%= button Spree.t(:update), 'icon-refresh' %>
      <span class="or"><%= Spree.t(:or) %></span>
        <%= link_to_with_icon 'icon-remove', Spree.t(:cancel), admin_active_sale_active_sale_event_url(@active_sale, @active_sale_event), :id => 'cancel_link', :class => 'button' %>
    </div>
  </fieldset>
<% end %>

app/views/spree/admin/sale_images/new.html.erb
<ul class="inline-menu">
  <li><%= button_link_to t('spree.active_sale.event.link.back'), edit_admin_active_sale_active_sale_event_url(@active_sale, @active_sale_event), :icon => 'icon-arrow-left' %></li>
</ul>


<%= form_for [:admin, @active_sale, @active_sale_event, @sale_image], :html => { :multipart => true } do |f| %>
  <fieldset data-hook="new_image">
    <legend align="center"><%= Spree.t(:new_image) %></legend>

      <%= render :partial => 'form', :locals => { :f => f } %>
    
      <div class="form-buttons filter-actions actions" data-hook="buttons">
        <%= button Spree.t(:save), 'icon-refresh' %>
        <span class="or"><%= Spree.t(:or) %></span>
        <%= link_to_with_icon 'icon-remove', Spree.t(:cancel), admin_active_sale_active_sale_event_url(@active_sale_event.active_sale, @active_sale_event), :id => 'cancel_link', :class => 'button' %>
      </div>
  </fieldset>
<% end %>