config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add this extension's routes here
  namespace :admin do
    resources :active_sales do
      collection do
        get  :eventables
        post :update_positions
      end
      member do
        get :get_children
      end
      resources :active_sale_events do
        member do
          put :update_events
        end
        resources :sale_images do
          collection do
            post :update_positions
          end
        end
      end
    end
  end
end

app/models/spree/active_sale.rb
# ActiveSales
# Active sales represent an entity for one sale at a time, just like a taxonomy in spree.
# For example: 'January 2013' sale, which can have many sale events in it.
#
module Spree
  class ActiveSale < Spree::SaleEvent
    validates :name, :presence => true
    validate :start_and_end_date_presence, :start_and_end_date_range

    has_many :active_sale_events
    has_one :root, :conditions => { :parent_id => nil }, :class_name => "Spree::ActiveSaleEvent",
                   :dependent => :destroy

    before_save :have_valid_position
    after_save :set_root

    default_scope :order => "#{self.table_name}.position"

    def self.config(&block)
      yield(Spree::ActiveSaleConfig)
    end

    private
      def set_root
        root_hash = self.serializable_hash
        root_hash["active_sale_id"] = self.id
        root_hash["type"] = "Spree::ActiveSaleEvent"
        %w(id created_at updated_at lft rgt parent_id).each{ |column| root_hash.delete(column) }
        if root
          root.update_attributes(root_hash)
        else
          self.root = Spree::ActiveSaleEvent.create!(root_hash, :without_protection => true)
        end
      end

      def start_and_end_date_presence
        errors.add(:start_date, I18n.t('spree.active_sale.event.validation.errors.date_empty')) if self.start_date.nil?
        errors.add(:end_date, I18n.t('spree.active_sale.event.validation.errors.date_empty')) if self.end_date.nil?
      end

      # This should validate the start and end date range between
      # its active_sale_events. To make sure that, root lives longer.
      def start_and_end_date_range
        unless self.start_date.nil? || self.end_date.nil?
          oldest_start_date = self.active_sale_events.not_blank_and_sorted_by(:start_date).first
          latest_end_date = self.active_sale_events.not_blank_and_sorted_by(:end_date).last
          errors.add(:start_date, I18n.t('spree.active_sale.event.validation.errors.invalid_root_dates')) if (oldest_start_date.nil? && latest_end_date.nil?) ? false : (self.start_date > oldest_start_date || self.end_date < latest_end_date)
        end
      end
  end
end

app/controllers/spree/admin/active_sales_controller.rb
module Spree
  module Admin
    class ActiveSalesController < ResourceController
      before_filter :load_active_sale_events, :only => [:new, :edit]
      before_filter :set_active_sale, :only => [:create, :update]
      respond_to :json, :only => [:get_children]

      def get_children
        @active_sale_events = Spree::ActiveSaleEvent.find(params[:parent_id]).children_sorted_by_position
        respond_with(@active_sale_events)
      end
      
      def index
        respond_with(@collection) do |format|
          format.html
          format.json { render :json => json_data }
        end
      end

      def show
        redirect_to edit_object_url(@active_sale)
      end

      def eventables
        search = params[:eventable_type].constantize.search(:name_cont => params[:name])
        render :json => search.result.map(&:name)
      end

      protected

        def collection
          return @collection if @collection.present?
          @search = Spree::ActiveSale.includes(:active_sale_events).ransack(params[:q])
          @collection = @search.result.page(params[:page]).per(Spree::ActiveSaleConfig[:admin_active_sales_per_page])
        end

        def load_active_sale_events
          if @active_sale.new_record?
            @active_sale_event = @active_sale.active_sale_events.build
          else
            @active_sale_event = @active_sale.root
            @active_sale_events = @active_sale.active_sale_events
          end
        end

        def set_active_sale
          return false if params[:active_sale_event].blank?
          params[:active_sale] = params[:active_sale_event]
          params[:active_sale].delete(:discount)
          object_name = params[:active_sale]
          get_eventable_object(object_name)
        end
    end
  end
end

app/helpers/spree/active_sales_helper.rb
module Spree
  module ActiveSalesHelper
    # Getter to load all_sale_events
    # Get the helper and load from cache when possible
    def all_sale_events
      @all_sale_events ||= Spree::SaleEvent.live_active
    end

    # Setter to set all_sale_events.
    # Set the helper and load from parameter when possible
    def all_sale_events=(sale_events)
      return Array.new unless sale_events.class == Array
      @all_sale_events = sale_events
    end

    # Get the helper and load from cache when possible
    def all_active_sale_events
      all_sale_events.select{ |e| e.type == "Spree::ActiveSaleEvent" && e.parent_id != nil }
    end

    # find sale event for the product or a taxon
    # pass taxon or product object in the argument
    def get_sale_event(object)
      if ["Spree::Product", "Spree::Taxon"].include? object.class.name
        active_sale_event = all_sale_events.detect{ |sale_event| (sale_event.eventable_type == object.class.name) && (sale_event.eventable_id == object.id) }
      end
      active_sale_event
    end

    # helper to load current_active_sale_event
    def current_active_sale_event
      all_sale_events.detect{ |sale_event| current_permalink?(sale_event.permalink) }
    end

    def current_active_sale_event=(active_sale_event)
      active_sale_event.nil? ? current_active_sale_event : active_sale_event
    end

    # check for current permalink using request
    # split with "?" as there can be parameters
    def current_permalink?(permalink = nil)
      return false if permalink.blank?
      request.path.split('/').reject(&:blank?).join('/') == permalink
    end
  end
end

app/views/spree/admin/active_sales/edit.html.erb
<%= render :partial => 'spree/admin/shared/list_events', :locals => { :active_sale => @active_sale, :active_sale_events => @active_sale_events } %>

app/views/spree/admin/active_sales/get_children.json.erb
[<% @active_sale_events.each_with_index do |t,i| %>
  { "attr" :
    { "id" : "<%= t.id %>", "parent_id" : "<%= t.parent_id %>" },
    "data" : "<%= raw(event_js_data(t)) %>"
    <% unless t.children.empty? %>
      ,"state" : "closed"
    <% end %>
  }<%= "," if i < (@active_sale_events.size - 1) %>
<% end %>]

app/views/spree/admin/active_sales/index.html.erb
<% content_for :page_title do %>
  <%= t('spree.active_sale.title.list') %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to t('spree.active_sale.link.new'), new_object_url, :icon => 'icon-plus', :id => 'admin_new_active_sale_link' %>
  </li>
<% end %>

<div id="new_active_sale" data-hook></div>

<table class="index sortable" id='listing_active_sales' data-hook data-sortable-link="<%= update_positions_admin_active_sales_url %>">
  <colgroup>
    <col style="width: 85%">
    <col style="width: 15%">
  </colgroup>
  <thead>
    <tr data-hook="active_sales_header">
      <th><%= t('spree.active_sale.active_record.name') %></th>
      <th class="actions"></th>
    </tr>
  </thead>
  <tbody>
    <% @active_sales.each do |active_sale| %>
      <tr id="<%= spree_dom_id active_sale %>" data-hook="active_sales_row" class="<%= cycle('odd', 'even')%>">
        <td>
          <span class="handle"></span>&nbsp;
          <%= active_sale.name %>
        </td>
        <td class="actions">
          <%= link_to_edit active_sale.id, :no_text => true %>
          <%= link_to_delete active_sale, :no_text => true %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @active_sales %>

<% content_for :sidebar_title do %>
  <%= Spree.t(:search) %>
<% end %>

<% content_for :sidebar do %>
  <div class="box align-center" data-hook="admin_active_sales_index_search">    
    <%= search_form_for [:admin, @search] do |f| %>
      <div class="field">
        <%= f.label Spree.t(:name) %> <br>
        <%= f.text_field :name_cont, :class => 'fullwidth' %>
      </div>
      <div data-hook="admin_active_sales_index_search_buttons">
        <%= button Spree.t(:search), 'icon-search' %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/spree/admin/active_sales/new.html.erb
<% content_for :page_title do %>
  <%= t('spree.active_sale.title.new') %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to t('spree.active_sale.link.back'), collection_url, :icon => 'icon-arrow-left', :id => 'back_to_active_sales_link' %>
  </li>
<% end %>

<div data-hook="admin_active_sale_new_form">
  <div id="active-sale-form-wrapper">
    
    <% if @active_sale.try(:errors).present? %>
      <%= render :partial => 'spree/shared/error_messages', :locals => { :target => @active_sale } %>
    <% end %>

    <%= form_for [:admin, @active_sale], :html => { :id => 'admin_active_sale_event' } do |form| %>
      <%= fields_for @active_sale_event do |event_form| %>
        <%= render :partial => 'spree/admin/active_sale_events/form', :locals => { :form => event_form } %>
      <% end %>
    <% end %>
  </div>
</div>