config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add this extension's routes here
  namespace :admin do
    resources :active_sales do
      collection do
        get  :eventables
        post :update_positions
      end
      member do
        get :get_children
      end
      resources :active_sale_events do
        member do
          put :update_events
        end
        resources :sale_images do
          collection do
            post :update_positions
          end
        end
      end
    end
  end
end

app/models/spree/active_sale_event.rb
# EVENTS
# Events represent an entity for active sale in a flash sale/ daily deal.
# There can be many events for one sale, just like taxonomies in spree.
#
module Spree
  class ActiveSaleEvent < Spree::SaleEvent
    acts_as_nested_set :dependent => :destroy, :polymorphic => true

    before_validation :update_permalink
    before_save :have_valid_position
    after_save :update_parent_active_sales, :update_active_sale_position

    has_many :sale_images, :as => :viewable, :dependent => :destroy, :order => 'position ASC'
    belongs_to :eventable, :polymorphic => true
    belongs_to :active_sale

    attr_accessible :description, :end_date, :eventable_id, :eventable_type, :is_active, :is_hidden, :is_permanent, :name, :permalink, :active_sale_id, :start_date, :eventable_name, :discount, :parent_id

    validates :name, :permalink, :eventable_id, :start_date, :end_date, :active_sale_id, :presence => true
    validates :eventable_type, :presence => true, :uniqueness => { :scope => :eventable_id, :message => I18n.t('spree.active_sale.event.validation.errors.live_event') }, :if => :live?

    scope :non_parents, lambda { where('parent_id IS NOT NULL') }

    # Spree::ActiveSaleEvent.is_live? method 
    # should only/ always represents live and active events and not just live events.
    def is_live? object
      object_class_name = object.class.name
      return object.live_and_active? if object_class_name == self.name
      %w(Spree::Product Spree::Variant Spree::Taxon).include?(object_class_name) ? object.live? : false
    end

    def update_permalink
      prefix = {"Spree::Taxon" => "t", "Spree::Product" => "products"}
      self.permalink = [prefix[self.eventable_type], self.eventable.permalink].join("/") unless self.eventable.nil?
    end

    # This callback basically makes sure that parents for an event lives longer.
    # Or at least parents live for the time when event is live.
    def update_parent_active_sales
      active_sale_events = self.self_and_ancestors
      parents = self.ancestors
      oldest_start_date = active_sale_events.not_blank_and_sorted_by(:start_date).first
      latest_end_date = active_sale_events.not_blank_and_sorted_by(:end_date).last
      parents.each{ |parent| 
        parent.update_attributes(:start_date => oldest_start_date) if parent.start_date.nil? ? true : (parent.start_date > oldest_start_date) 
        parent.update_attributes(:end_date => latest_end_date) if parent.end_date.nil? ? true : (parent.end_date < latest_end_date)
      }
    end

    def eventable_name
      eventable.try(:name)
    end

    def eventable_name=(name)
      self.eventable = self.eventable_type.constantize.find_by_name(name) if name.present?
    end

    def eventable_image_available?
      !!eventable.try(:image_available?)
    end

    def children_sorted_by_position
      self.children.sort_by{ |child| child.position.nil? ? 0 : child.position }
    end

    private
    def update_active_sale_position
      return true unless active_sale.position.nil?
      active_sale = self.active_sale
      active_sale.position = nil
      active_sale.save
    end
  end
end

app/controllers/spree/admin/active_sale_events_controller.rb
module Spree
  module Admin
    class ActiveSaleEventsController < ResourceController
      belongs_to 'spree/active_sale', :find_by => :id
      before_filter :load_active_sale, :only => [:index]
      before_filter :parent_id_for_event, :only => [:new, :edit, :create, :update]
      update.before :get_eventable
      respond_to :json, :only => [:update_events]

      def show
        redirect_to( :action => :edit )
      end

      def destroy
        @active_sale_event = Spree::ActiveSaleEvent.find(params[:id])
        @active_sale_event.destroy
        respond_with(@active_sale_event) { |format| format.json { render :json => '' } }
      end

      def update_events
        @active_sale_event.update_attributes(params[:active_sale_event])
        respond_with(@active_sale_event)
      end

      protected

        def collection
          return @collection if @collection.present?
          @search = Spree::ActiveSaleEvent.where(:active_sale_id => params[:active_sale_id]).ransack(params[:q])
          @collection = @search.result.page(params[:page]).per(Spree::ActiveSaleConfig[:admin_active_sale_events_per_page])
        end

        def load_active_sale
          @active_sale = Spree::ActiveSale.find(params[:active_sale_id])
        end

        def build_resource
          get_eventable unless params[object_name].nil?
          if parent_data.present?
            parent.send(controller_name).build(params[object_name])
          else
            model_class.new(params[object_name])
          end
        end

        def get_eventable
          object_name = params[:active_sale_event]
          get_eventable_object(object_name)
        end

        def parent_id_for_event
          params[:parent_id] ||= check_active_sale_event_params
          @parent_id = params[:parent_id]
          if @parent_id.blank?
            redirect_to edit_admin_active_sale_path(params[:active_sale_id]), :notice => I18n.t('spree.active_sale.event.parent_id_cant_be_nil')
          end
        end

        def check_active_sale_event_params(event = params[:active_sale_event])
          return nil if event.nil?
          parent_id = event[:parent_id]
          event.delete(:parent_id) if event[:parent_id].nil? || event[:parent_id] == "nil"
          parent_id
        end
    end
  end
end

app/helpers/spree/active_sale_events_helper.rb
module Spree
  module ActiveSaleEventsHelper
    
    def sale_event_timer(event = nil, layout = nil)
      return I18n.t('spree.active_sale.event.can_not_be_nil') if (event == nil) || (event.class.name != "Spree::ActiveSaleEvent")
      layout ||= '{dn} DAYS {hnn}{sep}{mnn}{sep}{snn}'
      content_tag(:span, I18n.t('spree.active_sale.event.ending_message'), :class => 'sale_event_message') + " " + content_tag(:span, event.end_date.strftime('%Y-%m-%dT%H:%M:%S'), "data-timer" => event.end_date.strftime('%Y-%m-%dT%H:%M:%S'), "data-layout" => layout, :class => 'sale_event_message_timer')
    end

    def method_missing(method_name, *args, &block)
      if image_style = image_style_from_method_name_for_sale(method_name)
        define_sale_image_method(image_style)
        self.send(method_name, *args)
      else
        super
      end
    end

    def sale_image_available?(sale_event)
      !sale_event.sale_images.empty? || sale_event.eventable_image_available?
    end

    private

    # Returns style of image or nil
    def image_style_from_method_name_for_sale(method_name)
      if style = method_name.to_s.sub(/_event_image$/, '')
        possible_styles = Spree::SaleImage.attachment_definitions[:attachment][:styles]
        style if style.in? possible_styles.with_indifferent_access
      end
    end

    def define_sale_image_method(style)
      self.class.send :define_method, "#{style}_event_image" do |sale_event, *options|
        options = options.first || {}
        if sale_event.sale_images.empty?
          image_tag "noimage/#{style}.png", options
        else
          image = sale_event.sale_images.first
          options.reverse_merge! :alt => image.alt.blank? ? sale_event.name : image.alt
          image_tag image.attachment.url(style), options
        end
      end
    end

    def event_js_data(event)
      return nil if event.blank?
      Spree::ActiveSaleConfig[:name_with_event_position?] ? "#{event.name.gsub('"','\"')} - #{I18n.t('spree.active_sale.event.active_record.position')}: #{event.position}" : event.name.gsub('"','\"')
    end
  end
end

app/views/spree/admin/active_sale_events/_form.html.erb
<% if @active_sale_event.try(:errors).present? %>
  <%= render :partial => 'spree/shared/error_messages', :locals => { :target => @active_sale_event } %>
<% end %>

  <fieldset data-hook="admin_active_sale_event_form_fields">

    <%= form.hidden_field :parent_id, :value => @parent_id %>

    <div class="clearfix">
      <div class="left eight columns alpha" data-hook="admin_active_sale_event_form_left">
        <%= form.field_container :name do %>
          <%= form.label :name, raw(t('spree.active_sale.event.active_record.name') + content_tag(:span, ' *', :class => 'required')) %>
          <%= form.text_field :name, :class => 'fullwidth' %>
          <%= form.error_message_on :name %>
        <% end %>
        <%= form.field_container :description do %>
          <%= form.label :description, t('spree.active_sale.event.active_record.description') %>
          <%= form.text_area :description, {:cols => 60, :rows => 10, :class => 'fullwidth'} %>
          <%= form.error_message_on :description %>
        <% end %>
      </div>

      <div class="right eight columns omega" data-hook="admin_active_sale_event_form_right">
        <div class="row">
          <div class="alpha four columns">
            <%= form.field_container :start_date do %>
              <%= form.label :start_date, t('spree.active_sale.event.active_record.start_date') %>
              <%= form.error_message_on :start_date %>
              <% if @active_sale_event.start_date? %>
                <% start_date = l(@active_sale_event.start_date, :format => t('spree.active_sale.event.datetimepicker.format')) %>
              <% else %>
                <% start_date = l(Time.zone.now, :format => t('spree.active_sale.event.datetimepicker.format')) %>
              <% end %>
              <%= form.text_field :start_date, :value => start_date, :class => 'timepicker' %>
            <% end %>
          </div>
  
          <div class="omega four columns">
            <%= form.field_container :end_date do %>
              <%= form.label :end_date, t('spree.active_sale.event.active_record.end_date') %>
              <%= form.error_message_on :end_date %>
              <% end_date = l((@active_sale_event.end_date? ? @active_sale_event.end_date : Time.zone.now+1.day), :format => t('spree.active_sale.event.datetimepicker.format')) %>
              <%= form.text_field :end_date, :value => end_date, :class => 'timepicker' %>
            <% end %>
          </div>
        </div>
        <div class="row">
          <div class="alpha four columns">
            <%= form.label :eventable, t('spree.active_sale.event.active_record.eventable_type', :default => :evenetable) %>
            <p class='hint'><%= t('spree.active_sale.event.eventable_hint') %></p>
            <%= form.select :eventable_type, [["Product","Spree::Product"], ["Taxon","Spree::Taxon"]], { :include_blank => false }, { :class => 'select2' } %>
            <%= form.error_message_on :eventable %>
          </div>
  
          <div class="omega four columns">
            <%= form.label :eventable_name, t('spree.active_sale.event.active_record.eventable_name', :default => :eventable_name) %>
            <p class='hint'><%= t('spree.active_sale.event.eventable_name_hint') %></p>
            <%= form.error_message_on :eventable_name %>
            <%= form.text_field :eventable_name, :class => 'autocomplete', :data => { :auto_complete_url => eventables_admin_active_sales_url } %>
          </div>
        </div>
        <div class="row">
          <div class="alpha four columns clearfix">
            <%= form.field_container :is_active, :class => ['checkbox'] do %>
              <label>
                <%= form.check_box :is_active %>
                <%= t('spree.active_sale.event.active_record.is_active') %>
                <%= form.error_message_on :is_active %>
              </label>
            <% end %>
  
            <%= form.field_container :is_hidden, :class => ['checkbox'] do %>
              <label>
                <%= form.check_box :is_hidden %>
                <%= t('spree.active_sale.event.active_record.is_hidden') %>
                <%= form.error_message_on :is_hidden %>
              </label>
            <% end %>
  
            <%= form.field_container :is_permanent, :class => ['checkbox'] do %>
              <label>
                <%= form.check_box :is_permanent %>
                <%= t('spree.active_sale.event.active_record.is_permanent') %>
                <%= form.error_message_on :is_permanent %>
              </label>
            <% end %>
          </div>
  
          <div class="omega four columns">
          <%= form.field_container :discount do %>
            <%= form.label :discount, t('spree.active_sale.event.active_record.discount', :default => :discount) %>
            <p class='hint'><%= t('spree.active_sale.event.discount_hint') %></p>
            <%= form.error_message_on :discount %>
            <%= form.text_field :discount, :size => 2, :maxlength => 2 %>
          <% end %>
          </div>
        </div>

      </div>
    </div>

    <% unless @active_sale_event.new_record? %>
      <ul class="inline-menu">
        <li><%= link_to_with_icon('icon-plus', Spree.t(:new_image), new_admin_active_sale_active_sale_event_sale_image_url(@active_sale, @active_sale_event), :id => 'new_sale_image_link', :class => 'button') %></li>
      </ul>
      <br/>
      <%= render 'spree/admin/shared/sale_images' %>
    <% end %>


    <p class="form-buttons" data-hook="admin_active_sale_form_buttons">
      <% if @active_sale_event.new_record? %>
        <%= render :partial => 'spree/admin/shared/new_resource_links' %>
      <% else %>
        <%= render :partial => 'spree/admin/shared/edit_resource_links' %>
      <% end %>
    </p>
  </fieldset>

<%= javascript_tag do -%>
  var properties = "<%= raw(@properties.to_json) %>";

  $("#admin_active_sale_event input.autocomplete").on("keydown", function(){
    var eventable_type = $('#active_sale_event_eventable_type :selected').val();
    var eventable_name = $('#active_sale_event_eventable_name').val();
    var url = $(this).data('auto-complete-url')
    already_auto_completed = $(this).is('ac_input');
    if (!already_auto_completed) {
      $(this).autocomplete({
        source: url+"?eventable_type="+eventable_type+"&name="+eventable_name
      });
      $(this).focus();
    }
  });
<% end -%>

app/views/spree/admin/active_sale_events/edit.html.erb
<% content_for :page_title do %>
  <%= @active_sale.name %> &#62; <%= @active_sale_event.name %> &#62; <%= t('spree.active_sale.event.title.edit') %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to t('spree.active_sale.link.edit'), [:edit, :admin, @active_sale], :icon => 'icon-arrow-left', :id => 'admin_active_sales_link' %>
  </li>
<% end %>

<div data-hook="admin_active_sale_event_edit_form">
  <div id="active-sale-event-form-wrapper">
    <%= form_for [:admin, @active_sale, @active_sale_event], :html => { :id => 'admin_active_sale_event', :multipart => true } do |form| %>
      <%= render :partial => 'form', :locals => { :form => form } %>
    <% end %>
  </div>
</div>

app/views/spree/admin/active_sale_events/index.html.erb
<%= render :partial => 'spree/admin/shared/list_events', :locals => { :active_sale => @active_sale, :active_sale_events => @active_sale_events } %>

app/views/spree/admin/active_sale_events/new.html.erb
<% content_for :page_title do %>
  <%= @active_sale.name %> &#62; <%= t('spree.active_sale.event.title.new') %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to t('spree.active_sale.event.link.back'), [:admin, @active_sale, @active_sale_event], :icon => 'icon-arrow-left', :id => 'admin_new_active_sale_event_link' %>
  </li>
<% end %>

<div data-hook="admin_active_sale_event_edit_form">
  <div id="active-sale-event-form-wrapper">
    <%= form_for [:admin, @active_sale, @active_sale_event], :html => { :id => 'admin_active_sale_event', :multipart => true } do |form| %>
      <%= render :partial => 'form', :locals => { :form => form } %>
    <% end %>
  </div>
</div>