config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add this extension's routes here
  namespace :admin do
    resources :active_sales do
      collection do
        get  :eventables
        post :update_positions
      end
      member do
        get :get_children
      end
      resources :active_sale_events do
        member do
          put :update_events
        end
        resources :sale_images do
          collection do
            post :update_positions
          end
        end
      end
    end
  end
end

app/views/spree/admin/shared/_js_head.html.erb
<% content_for :head do %>
  <%= javascript_tag "var active_sale_id = #{@active_sale.id};
    var loading = '#{escape_javascript Spree.t(:loading)}';
    var new_active_sale_event = '#{escape_javascript t('spree.active_sale.event.link.new')}';
    var server_error = '#{escape_javascript Spree.t(:server_error)}';
    var active_sale_tree_error = '#{escape_javascript t('spree.active_sale.tree_error')}';"
  %>
<% end %>

app/views/spree/admin/shared/_list_events.html.erb
<%= render :partial => 'spree/admin/shared/js_head' %>

<% content_for :page_title do %>
  <%= t('spree.active_sale.title.edit') %> &#62; <%= @active_sale.name %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to t('spree.active_sale.link.back'), collection_url, :icon => 'icon-arrow-left', :id => 'admin_new_active_sale_link' %>
  </li>
<% end %>

<div id="ajax_error" class="errorExplanation" style="display:none;"></div>

<fieldset class="no-border-top">
  <div>
    <%= label_tag nil, Spree.t(:tree) %><br />
    <div id="active_sale_tree" class="tree" data-url="<%= admin_active_sale_active_sale_events_path @active_sale %>"></div>
  </div>
  <div id="progress" style="display:none;">
    <%= image_tag 'spinner.gif', :title => 'Spinner', :style => "vertical-align:bottom;" %> <%= Spree.t(:updating) %>..
  </div>

  <p class='hint info'>
    <%= t('spree.active_sale.event.active_sale_tree_hint') %>
  </p>

  <br>
</fieldset>

<% content_for :head do %>
  <%= javascript_tag do -%>
    var initial = [
      { "attr" :
      { "id" : "<%= @active_sale.root.try(:id) %>", "rel" : "root", "parent_id" : "nil" },
      "data" : "<%= escape_javascript(raw(@active_sale.root.try(:name))) %>",
      "state" : "open",
      "children" : [
        <% unless @active_sale.root.nil? %>
          <% @active_sale.root.children_sorted_by_position.each_with_index do |event,i| %>
            {
              "attr" :
              { "id" : "<%= event.id %>", "parent_id" : "<%= event.parent_id %>" },
              "data" : "<%= escape_javascript(raw(event_js_data(event))) %>"
              <% unless event.children.empty? %>
                ,"state" : "closed"
              <% end %>
            }<%= ',' if i < (@active_sale.root.children.size - 1) %>
          <% end %>
        <% end %>
      ]
        }
    ];
  <% end -%>
<% end %>

app/views/spree/admin/shared/_sale_images.html.erb
<div id="images" data-hook></div>

<% unless @active_sale_event.sale_images.any? %>
  <div class="no-objects-found">
    <%= t('spree.active_sale.event.no_image') %>
  </div>
<% else %>
  <table class="index sortable" data-hook="images_table" data-sortable-link="<%= update_positions_admin_active_sale_active_sale_event_sale_images_url(@active_sale, @active_sale_event) %>">
    <colgroup>
      <col style="width: 5%">
      <col style="width: 10%">
      <col style="width: 45%">
      <col style="width: 15%">
    </colgroup>
    <thead>
      <tr data-hook="images_header">
        <th colspan="2"><%= Spree.t(:thumbnail) %></th>
        <th><%= Spree.t(:alt_text) %></th>
        <th class="actions"></th>
      </tr>
    </thead>

    <tbody>
      <% (@active_sale_event.sale_images).each do |image| %>
        <tr id="<%= spree_dom_id image %>" data-hook="images_row" class="<%= cycle('odd', 'even')%>">
          <td class="no-border">
            <span class="handle"></span>
          </td>
          <td>
            <%= link_to image_tag(image.attachment.url(:mini)), image.attachment.url(:original) %>
          </td>
          <td><%= image.alt %></td>
          <td class="actions">
            <%= link_to_edit_url [:edit, :admin, @active_sale, @active_sale_event, image], :no_text => true %>
            <%= link_to_delete image, { :url => [:admin, @active_sale, @active_sale_event, image], :no_text => true } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/spree/admin/shared/_translations.html.erb
<script>
  Spree.translations = <%==
  { :date_picker    => I18n.t(:js_format,
                              :scope => 'spree.date_picker',
                              :default => 'yy/mm/dd'),
    :abbr_day_names      => I18n.t(:abbr_day_names, :scope => :date),
    :add                 => I18n.t('spree.add'),
    :are_you_sure_delete => I18n.t('spree.are_you_sure_delete'),
    :bill_address        => I18n.t('spree.bill_address'),
    :choose_a_customer   => I18n.t('spree.choose_a_customer'),
    :confirm_delete      => I18n.t('spree.confirm_delete'),
    :cut                 => I18n.t('spree.cut'),
    :destroy             => I18n.t('spree.destroy'),
    :edit                => I18n.t('spree.edit'),
    :loading             => I18n.t('spree.loading'),
    :month_names         => I18n.t(:month_names, :scope => :date).delete_if(&:blank?),
    :more                => I18n.t('spree.more'),
    :name                => I18n.t('spree.name'),
    :next                => I18n.t('spree.next'),
    :no_results          => I18n.t('spree.no_results'),
    :on_hand             => I18n.t('spree.on_hand'),
    :paste               => I18n.t('spree.paste'),
    :previous            => I18n.t('spree.previous'),
    :remove              => I18n.t('spree.remove'),
    :rename              => I18n.t('spree.rename'),
    :searching           => I18n.t('spree.searching'),
    :sku                 => I18n.t('spree.sku'),
    :type_to_search      => I18n.t('spree.type_to_search'),
    :taxon_placeholder   => I18n.t('spree.taxon_placeholder'),
    :value               => I18n.t('spree.value')
  }.to_json
%>
</script>

<script>
  Spree.datetime_translations = <%==
  { :date_format      => I18n.t('spree.active_sale.event.datetimepicker.js_date_format',
                              :default => 'yy/mm/dd'),
    :time_format      => I18n.t('spree.active_sale.event.datetimepicker.js_format',
                              :default => 'hh:mm:ss tt z'),
    :time_only_title  => I18n.t('spree.active_sale.event.datetimepicker.time_only_title', 
                              :default => 'Time Only'),
    :time_text        => I18n.t('spree.active_sale.event.datetimepicker.time_text',
                              :default => 'Time'),
    :hour_text        => I18n.t('spree.active_sale.event.datetimepicker.hour_text',
                              :default => 'Hour'),
    :minute_text      => I18n.t('spree.active_sale.event.datetimepicker.minute_text',
                              :default => 'Minute'),
    :second_text      => I18n.t('spree.active_sale.event.datetimepicker.second_text',
                              :default => 'Second'),
    :current_text     => I18n.t('spree.active_sale.event.datetimepicker.current_text',
                              :default => 'Current'),
    :close_text       => I18n.t('spree.active_sale.event.datetimepicker.close_text',
                              :default => 'Close')
  }.to_json
%>
</script>